sudo: false
language: c
services:
  - docker
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- ci/before_install.sh
script:
- ci/script.sh
deploy:
  provider: releases
  api_key:
    secure: aOrH7O44if7TdnSOuvsnjCO5m8v1JFxp/y4MWABEwc6NlK3WoJtpW+aF2guaps3RX7C7gMenhC7BQ3E3LjWvceH8h1d6D5Mm53RM9GVnpIckCyp5vwADeMBL3wR6Xlr5xMub7QwSNeZbLWORM9GqYATB+vKhp/dmUlWbQOhlZsRkoPQKUWjK7LXCLu3qJp39oZBrsfZuhWXNhBZvyeMJOOycpXoPVVWqp+nAop5dSYXLHWUY3l/XR40oBd6HxvWXzfjlQkmqBkZKfQZ0wvwzrB/6k48Z+8CTQa1cbC5obBB8gAwbhJF2w06LPP8+LI+BnGwVRrQh7cCmmFQ7hxW41a2IFi5Ar0Gsuei5eGq/nzwp3i5LRKLHKJvVEOENOpRESC8dZCu2Cq8oTBJIFTUx97rVBESwwbOiNfowheKqu7hocuvQP1kJ3DXqinUig1+Df3+J8AGhKgBMaRpFYYU4NwpFkSllE3KqFPuu+5YV82/BWezEpKcawqu/ZhnGUp4TpZJe69y8tPvu9OYP2p6aTbDhLnczs3+tdx6K0+qNZBXcY+aMvMy9vTtiSqXlsb2kSo/xCEQ1S9owL56tdI1Ux8pDQm46b69IgHJRJ4sNOB26P5fLfDTMXhNIIsIPtGmAmHfMi3GanZ6UQX9e8wxu4GT69o1xopkmvDBztIMkg6Q=
  file: resizedisk_linux_amd64.tar.gz
  on:
    repo: shokohara/haskell-gcp-resizedisk
