name: resizedisk
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: shokohara/haskell-resizedisk
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - App
  dependencies:
  - base >=4.7 && <5
  - bytestring
  - yaml
  - aeson
  - aeson-casing
  - process
  - servant-server
  - text
  - monad-logger
  - transformers
  - wai-logger
  - aeson-pretty
  - gogol
  - gogol-core
  - gogol-compute
  - gogol-pubsub
  - random
  - gogol-storage
  - http-client
  - conduit
  - conduit-extra
  - lens
  - resourcet
  - here
  - lens-aeson
  - HDBC
  - HTTP
  - uuid
executables:
  resizedisk-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - resizedisk
    - wai-logger
    - wai
    - text
    - warp
tests:
  resizedisk-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - resizedisk
    - hspec
    - hspec-discover
    - hspec-wai
    - hspec-wai-json
    - aeson
    - http-types
    - bytestring
    - QuickCheck
    - quickcheck-text
