name: resizedisk
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: shokohara/haskell-resizedisk
extra-source-files:
- README.md
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - App
  - Option
  dependencies:
  - base >=4.7 && <5
  - process
  - text
  - gogol
  - gogol-compute
  - gogol-storage
  - http-client
  - lens
  - resourcet
executables:
  resizedisk:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - resizedisk
    - optparse-applicative
tests:
  resizedisk-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - resizedisk
    - hspec
    - hspec-discover

